{% set name = "aqme" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aqme-{{ version }}.tar.gz
  sha256: f1222f1b5d06c53677c9b8f78f4eb8198677a07829d67c7672c46783676b47c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase
    - cclib
    - cffi
    - matplotlib-base
    - numpy
    - pandas
    - progress
    - python >=3.6
    - pyyaml
    - seaborn
    - openbabel
    - rdkit

test:
  imports:
    - aqme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jvalegre/aqme
  summary: Automated Quantum Mechanical Environments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvalegre
    - shreesowndarya
