{% set name = "aqme" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aqme-{{ version }}.tar.gz
  sha256: 43085144441e6c36a9c6a83a145e37df3dbc2183dab7b3fa604bf578bc04baab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase
    - cclib
    - cffi
    - matplotlib-base
    - numpy
    - pandas
    - progress
    - python >=3.6
    - pyyaml
    - seaborn
    - openbabel
    - rdkit
    - goodvibes
    - py3Dmol
    - ipywidgets
    - dbstep

test:
  imports:
    - aqme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jvalegre/aqme
  summary: Automated Quantum Mechanical Environments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvalegre
    - shreesowndarya
